// Product data for Kondappali Toys - USA Edition with USD pricing
const products = [
    {
        id: 1,
        name: "Dancing Doll (Thanjavur Style)",
        category: "decorative",
        price: 1.00,
        originalPrice: 29.99,
        image: "images/dancing-doll-thanjavur_400.jpg",
        images: ["images/dancing-doll-thanjavur_800.jpg"],
        description: "The iconic Kondappali dancing doll in traditional Thanjavur style, featuring a dancer in elegant pose with vibrant pink and gold attire. Hand-carved from soft wood and painted with natural dyes.",
        dimensions: "Height: 8 inches, Width: 4 inches",
        weight: "9 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 45,
        inStock: true,
        featured: true,
        popularity: 95
    },
    {
        id: 2,
        name: "Royal Elephants with Ambari Set",
        category: "animals",
        price: 42.00,
        originalPrice: 49.99,
        image: "images/royal-elephants-ambari_400.jpg",
        images: ["images/royal-elephants-ambari_800.jpg"],
        description: "A majestic pair of decorated elephants carrying royal howdahs (ambari). Each piece showcases intricate carving and vibrant traditional colors.",
        dimensions: "Large: 6 inches, Medium: 4 inches",
        weight: "14 oz",
        artisan: "Master Artisan",
        rating: 4.9,
        reviews: 62,
        inStock: true,
        featured: true,
        popularity: 98
    },
    {
        id: 3,
        name: "Double Bullock Cart",
        category: "village-life",
        price: 35.99,
        originalPrice: 39.99,
        image: "images/double-bullock-cart_400.jpg",
        images: ["images/double-bullock-cart_800.jpg"],
        description: "A charming depiction of rural life featuring two colorful bulls pulling a traditional cart with a farmer. This piece captures the essence of village transportation and agricultural heritage.",
        dimensions: "Length: 10 inches, Height: 5 inches",
        weight: "12 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 38,
        inStock: true,
        featured: true,
        popularity: 85
    },
    {
        id: 4,
        name: "Ramayana Characters Set",
        category: "deities",
        price: 89.99,
        originalPrice: 99.99,
        image: "images/ramayana-set_400.jpg",
        images: ["images/ramayana-set_800.jpg"],
        description: "Complete set of Ramayana characters including Lord Rama, Sita, Lakshmana, and Hanuman. Each figurine meticulously crafted. A collector's masterpiece.",
        dimensions: "Each figure: 4-5 inches",
        weight: "28 oz",
        artisan: "Master Artisan",
        rating: 5.0,
        reviews: 28,
        inStock: true,
        featured: true,
        popularity: 92
    },
    {
        id: 5,
        name: "Festival Celebration Scene",
        category: "village-life",
        price: 64.99,
        originalPrice: 74.99,
        image: "images/bhogi-festival-scene_400.jpg",
        images: ["images/bhogi-festival-scene_800.jpg"],
        description: "An elaborate diorama showcasing a traditional festival celebration with bonfire, villagers, and festive elements. Perfect for holiday decorations.",
        dimensions: "Base: 12 x 8 inches, Height: 6 inches",
        weight: "21 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 22,
        inStock: true,
        featured: false,
        popularity: 78
    },
    {
        id: 6,
        name: "Village Woman Cooking",
        category: "village-life",
        price: 18.99,
        originalPrice: 21.99,
        image: "images/woman-making-chapati_400.jpg",
        images: ["images/woman-making-chapati_800.jpg"],
        description: "A colorful depiction of a traditional village woman preparing food. This piece celebrates everyday life and domestic traditions.",
        dimensions: "Height: 5 inches, Width: 4 inches",
        weight: "7 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 31,
        inStock: true,
        featured: false,
        popularity: 72
    },
    {
        id: 7,
        name: "Dancing Dolls Set (5 pieces)",
        category: "decorative",
        price: 55.99,
        originalPrice: 64.99,
        image: "images/dancing-dolls-set_400.jpg",
        images: ["images/dancing-dolls-set_800.jpg"],
        description: "A beautiful set of five dancing dolls in colorful traditional attire. Perfect for home decor or as a unique gift.",
        dimensions: "Height: 5-7 inches each",
        weight: "16 oz",
        artisan: "Master Artisan",
        rating: 4.9,
        reviews: 56,
        inStock: true,
        featured: true,
        popularity: 90
    },
    {
        id: 8,
        name: "Decorative Deity Figure",
        category: "deities",
        price: 44.00,
        originalPrice: 51.99,
        image: "images/balaji-wooden-decorative_400.jpg",
        images: ["images/balaji-wooden-decorative_800.jpg"],
        description: "Divine decorative piece with intricate wooden lacquer work. The detailed ornaments and expressions showcase the artisan's mastery.",
        dimensions: "Height: 6 inches",
        weight: "13 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 47,
        inStock: true,
        featured: true,
        popularity: 88
    },
    {
        id: 9,
        name: "Decorated Cow Figurine",
        category: "animals",
        price: 29.99,
        originalPrice: 35.99,
        image: "images/decorated-cow-figurine_400.jpg",
        images: ["images/decorated-cow-figurine_800.jpg"],
        description: "Beautifully decorated sacred cow figurine with bells and traditional ornaments. A symbol of prosperity and good fortune.",
        dimensions: "Height: 7 inches, Width: 5 inches",
        weight: "10 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 34,
        inStock: true,
        featured: false,
        popularity: 82
    },
    {
        id: 10,
        name: "Folk Dancers on Horses",
        category: "decorative",
        price: 32.99,
        originalPrice: 37.99,
        image: "images/poikkal-kuthirai-dancers_400.jpg",
        images: ["images/poikkal-kuthirai-dancers_800.jpg"],
        description: "Traditional folk dancers in vibrant attire on decorative horses. This piece represents a famous regional dance form.",
        dimensions: "Height: 8 inches, Length: 7 inches",
        weight: "11 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 29,
        inStock: true,
        featured: false,
        popularity: 75
    },
    {
        id: 11,
        name: "Palm Tree Climbing Scene",
        category: "village-life",
        price: 27.99,
        originalPrice: 31.99,
        image: "images/toddy-tapper-scene_400.jpg",
        images: ["images/toddy-tapper-scene_800.jpg"],
        description: "A heartwarming scene of a villager climbing a palm tree with others below. A tribute to rural occupations and village life.",
        dimensions: "Height: 8 inches, Width: 6 inches",
        weight: "11 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 25,
        inStock: true,
        featured: false,
        popularity: 70
    },
    {
        id: 12,
        name: "Standing Deity Figure",
        category: "deities",
        price: 75.99,
        originalPrice: 84.99,
        image: "images/vishnu-balaji-standing_400.jpg",
        images: ["images/vishnu-balaji-standing_800.jpg"],
        description: "Magnificent standing deity figurine with detailed ornaments and traditional iconography. A masterpiece of craftsmanship.",
        dimensions: "Height: 10 inches, Base: 4 x 4 inches",
        weight: "19 oz",
        artisan: "Master Artisan",
        rating: 4.9,
        reviews: 19,
        inStock: true,
        featured: true,
        popularity: 86
    },
    {
        id: 13,
        name: "Wooden Ganesha",
        category: "deities",
        price: 23.99,
        originalPrice: 27.99,
        image: "images/wooden-ganesha_400.jpg",
        images: ["images/wooden-ganesha_800.jpg"],
        description: "Adorable wooden Lord Ganesha figurine in traditional style. Brings blessings and removes obstacles from your home.",
        dimensions: "Height: 5 inches",
        weight: "6 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 42,
        inStock: true,
        featured: false,
        popularity: 84
    },
    {
        id: 14,
        name: "Single Bullock Cart",
        category: "village-life",
        price: 25.99,
        originalPrice: 29.99,
        image: "images/single-bullock-cart_400.jpg",
        images: ["images/single-bullock-cart_800.jpg"],
        description: "Classic single bullock cart with blue accents and detailed farmer figurine. Represents traditional rural transportation.",
        dimensions: "Length: 8 inches, Height: 4 inches",
        weight: "10 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 33,
        inStock: true,
        featured: false,
        popularity: 76
    },
    {
        id: 15,
        name: "Egg-Shaped Women Dolls (Pair)",
        category: "decorative",
        price: 16.99,
        originalPrice: 19.99,
        image: "images/egg-shaped-women-dolls_400.jpg",
        images: ["images/egg-shaped-women-dolls_800.jpg"],
        description: "Charming pair of egg-shaped women dolls in traditional dress. Perfect for home decor and gifting.",
        dimensions: "Height: 4 inches each",
        weight: "5 oz",
        artisan: "Master Artisan",
        rating: 4.4,
        reviews: 28,
        inStock: true,
        featured: false,
        popularity: 68
    },
    {
        id: 16,
        name: "Palanquin with Bearers",
        category: "village-life",
        price: 49.99,
        originalPrice: 57.99,
        image: "images/palki-palanquin-bearers_400.jpg",
        images: ["images/palki-palanquin-bearers_800.jpg"],
        description: "Traditional palanquin with bearers carrying a bride. A beautiful piece depicting wedding traditions.",
        dimensions: "Length: 12 inches, Height: 6 inches",
        weight: "16 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 21,
        inStock: true,
        featured: false,
        popularity: 74
    },
    {
        id: 17,
        name: "Bull with Musicians",
        category: "village-life",
        price: 35.99,
        originalPrice: 41.99,
        image: "images/gangireddu-musicians_400.jpg",
        images: ["images/gangireddu-musicians_800.jpg"],
        description: "Traditional decorated bull performance scene with musicians playing instruments. A glimpse of folk entertainment.",
        dimensions: "Base: 8 x 6 inches, Height: 5 inches",
        weight: "13 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 27,
        inStock: true,
        featured: false,
        popularity: 73
    },
    {
        id: 18,
        name: "Green Parrots Pair",
        category: "animals",
        price: 13.99,
        originalPrice: 16.99,
        image: "images/green-parrots-pair_400.jpg",
        images: ["images/green-parrots-pair_800.jpg"],
        description: "Adorable pair of green parrots in vibrant colors. These cheerful birds add life to any space.",
        dimensions: "Height: 3 inches each",
        weight: "4 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 35,
        inStock: true,
        featured: false,
        popularity: 71
    },
    {
        id: 19,
        name: "Wooden Fish",
        category: "animals",
        price: 11.99,
        originalPrice: 14.99,
        image: "images/wooden-fish_400.jpg",
        images: ["images/wooden-fish_800.jpg"],
        description: "Beautifully crafted wooden fish in orange-red color. Symbol of prosperity and good fortune.",
        dimensions: "Length: 6 inches",
        weight: "4 oz",
        artisan: "Master Artisan",
        rating: 4.4,
        reviews: 22,
        inStock: true,
        featured: false,
        popularity: 65
    },
    {
        id: 20,
        name: "Woman Churning Butter",
        category: "village-life",
        price: 17.99,
        originalPrice: 20.99,
        image: "images/woman-making-butter_400.jpg",
        images: ["images/woman-making-butter_800.jpg"],
        description: "Traditional village woman churning butter with pots. A nostalgic scene from rural households.",
        dimensions: "Height: 4 inches, Base: 5 x 4 inches",
        weight: "7 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 24,
        inStock: true,
        featured: false,
        popularity: 69
    },
    {
        id: 21,
        name: "Village Couple",
        category: "village-life",
        price: 21.99,
        originalPrice: 25.99,
        image: "images/village-couple_400.jpg",
        images: ["images/village-couple_800.jpg"],
        description: "Traditional village couple figurines in colorful attire. Perfect representation of rural life.",
        dimensions: "Height: 5 inches each",
        weight: "8 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 30,
        inStock: true,
        featured: false,
        popularity: 72
    },
    {
        id: 22,
        name: "Woman at Spinning Wheel",
        category: "village-life",
        price: 19.99,
        originalPrice: 23.99,
        image: "images/woman-spinning-wheel_400.jpg",
        images: ["images/woman-spinning-wheel_800.jpg"],
        description: "Woman working on traditional spinning wheel. Represents the cottage industries of rural regions.",
        dimensions: "Height: 4 inches, Base: 5 x 4 inches",
        weight: "6 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 19,
        inStock: true,
        featured: false,
        popularity: 67
    },
    {
        id: 23,
        name: "Hexagonal Decorative Boxes Set",
        category: "decorative",
        price: 29.99,
        originalPrice: 35.99,
        image: "images/hexagonal-rangoli-boxes_400.jpg",
        images: ["images/hexagonal-rangoli-boxes_800.jpg"],
        description: "Colorful hexagonal boxes with traditional designs. Perfect for storing small items or as decorative pieces.",
        dimensions: "Each: 3 x 3 inches",
        weight: "11 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 26,
        inStock: true,
        featured: false,
        popularity: 75
    },
    {
        id: 24,
        name: "Square Decorative Tiles Set",
        category: "decorative",
        price: 23.99,
        originalPrice: 27.99,
        image: "images/square-kolam-tiles_400.jpg",
        images: ["images/square-kolam-tiles_800.jpg"],
        description: "Set of colorful square tiles with traditional patterns. Great for wall decor or table display.",
        dimensions: "Each: 4 x 4 inches",
        weight: "9 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 23,
        inStock: true,
        featured: false,
        popularity: 73
    },
    {
        id: 25,
        name: "Pot Lady Figurine",
        category: "decorative",
        price: 14.99,
        originalPrice: 17.99,
        image: "images/pot-lady-figurine_400.jpg",
        images: ["images/pot-lady-figurine_800.jpg"],
        description: "Traditional pot-shaped lady figurine with colorful decorations. A unique piece of folk art.",
        dimensions: "Height: 6 inches",
        weight: "6 oz",
        artisan: "Master Artisan",
        rating: 4.4,
        reviews: 20,
        inStock: true,
        featured: false,
        popularity: 66
    },
    {
        id: 26,
        name: "Stacking Rings Tower",
        category: "decorative",
        price: 12.99,
        originalPrice: 15.99,
        image: "images/stacking-rings-tower_400.jpg",
        images: ["images/stacking-rings-tower_800.jpg"],
        description: "Colorful stacking rings tower with traditional motifs. Both decorative and educational toy for children.",
        dimensions: "Height: 8 inches",
        weight: "6 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 32,
        inStock: true,
        featured: false,
        popularity: 70
    },
    {
        id: 27,
        name: "Dancing Dolls Black Dress (Pair)",
        category: "decorative",
        price: 27.99,
        originalPrice: 32.99,
        image: "images/dancing-dolls-black_400.jpg",
        images: ["images/dancing-dolls-black_800.jpg"],
        description: "Elegant pair of dancing dolls in black and gold attire. Sophisticated pieces for discerning collectors.",
        dimensions: "Height: 7 inches each",
        weight: "10 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 18,
        inStock: true,
        featured: false,
        popularity: 77
    },
    {
        id: 28,
        name: "Cobbler at Work Scene",
        category: "village-life",
        price: 16.99,
        originalPrice: 19.99,
        image: "images/cobbler-scene_400.jpg",
        images: ["images/cobbler-scene_800.jpg"],
        description: "Traditional cobbler/shoemaker at work scene. Celebrates the skilled craftsmen of village life.",
        dimensions: "Height: 4 inches, Base: 4 x 3 inches",
        weight: "5 oz",
        artisan: "Master Artisan",
        rating: 4.4,
        reviews: 17,
        inStock: true,
        featured: false,
        popularity: 64
    },
    {
        id: 29,
        name: "Women Grinding at Mortar",
        category: "village-life",
        price: 21.99,
        originalPrice: 25.99,
        image: "images/women-grinding-mortar_400.jpg",
        images: ["images/women-grinding-mortar_800.jpg"],
        description: "Two women working together at a traditional grinding mortar. Depicts the communal spirit of village life.",
        dimensions: "Height: 5 inches, Base: 5 x 4 inches",
        weight: "8 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 21,
        inStock: true,
        featured: false,
        popularity: 71
    },
    {
        id: 30,
        name: "Decorative Turtles Set (4 pieces)",
        category: "animals",
        price: 17.99,
        originalPrice: 20.99,
        image: "images/decorative-turtles_400.jpg",
        images: ["images/decorative-turtles_800.jpg"],
        description: "Set of four decorative wooden turtles with intricate patterns. Symbol of longevity and wisdom.",
        dimensions: "Various sizes: 2-3 inches",
        weight: "7 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 25,
        inStock: true,
        featured: false,
        popularity: 69
    },
    {
        id: 31,
        name: "Village Couple with Pot",
        category: "village-life",
        price: 23.99,
        originalPrice: 27.99,
        image: "images/village-couple-pot_400.jpg",
        images: ["images/village-couple-pot_800.jpg"],
        description: "Village man with pipe and woman carrying pot. Classic representation of rural life.",
        dimensions: "Height: 6 inches each",
        weight: "9 oz",
        artisan: "Master Artisan",
        rating: 4.6,
        reviews: 24,
        inStock: true,
        featured: false,
        popularity: 72
    },
    {
        id: 32,
        name: "Harvest Festival Display",
        category: "decorative",
        price: 26.99,
        originalPrice: 30.99,
        image: "images/pongal-pot-sugarcane_400.jpg",
        images: ["images/pongal-pot-sugarcane_800.jpg"],
        description: "Traditional harvest festival display with pot and crossed sugarcane. Perfect for seasonal celebrations.",
        dimensions: "Height: 8 inches, Base: 6 x 6 inches",
        weight: "11 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 28,
        inStock: true,
        featured: false,
        popularity: 76
    },
    {
        id: 33,
        name: "Temple Arch Display",
        category: "deities",
        price: 31.99,
        originalPrice: 36.99,
        image: "images/tirupati-balaji-arch_400.jpg",
        images: ["images/tirupati-balaji-arch_800.jpg"],
        description: "Miniature temple arch with deity figure. A sacred piece for your home temple or display.",
        dimensions: "Height: 5 inches, Width: 4 inches",
        weight: "7 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 31,
        inStock: true,
        featured: false,
        popularity: 79
    },
    {
        id: 34,
        name: "Temple Arch with Ganesha",
        category: "deities",
        price: 35.99,
        originalPrice: 41.99,
        image: "images/temple-arch-ganesha_400.jpg",
        images: ["images/temple-arch-ganesha_800.jpg"],
        description: "Beautiful temple arch setup with Lord Ganesha and bells. Brings divine blessings to your home.",
        dimensions: "Height: 8 inches, Width: 6 inches",
        weight: "12 oz",
        artisan: "Master Artisan",
        rating: 4.9,
        reviews: 35,
        inStock: true,
        featured: true,
        popularity: 85
    },
    {
        id: 35,
        name: "Egg-Shaped Dolls Set (5 pieces)",
        category: "decorative",
        price: 21.99,
        originalPrice: 25.99,
        image: "images/egg-shaped-dolls-five_400.jpg",
        images: ["images/egg-shaped-dolls-five_800.jpg"],
        description: "Set of five colorful egg-shaped dolls in different dress colors. Cheerful addition to any home.",
        dimensions: "Height: 3-4 inches each",
        weight: "7 oz",
        artisan: "Master Artisan",
        rating: 4.5,
        reviews: 29,
        inStock: true,
        featured: false,
        popularity: 71
    },
    {
        id: 36,
        name: "Round Decorative Coasters Set",
        category: "decorative",
        price: 15.99,
        originalPrice: 18.99,
        image: "images/round-kolam-coasters_400.jpg",
        images: ["images/round-kolam-coasters_800.jpg"],
        description: "Set of four round coasters with traditional designs. Functional art for your home.",
        dimensions: "Diameter: 3.5 inches each",
        weight: "6 oz",
        artisan: "Master Artisan",
        rating: 4.4,
        reviews: 22,
        inStock: true,
        featured: false,
        popularity: 67
    },
    {
        id: 37,
        name: "Decorative Bowl with Diyas",
        category: "decorative",
        price: 43.99,
        originalPrice: 49.99,
        image: "images/urli-bowl-diyas_400.jpg",
        images: ["images/urli-bowl-diyas_800.jpg"],
        description: "Decorative bowls surrounded by diyas for floating flowers. Creates a serene ambiance for any occasion.",
        dimensions: "Diameter: 8 inches each",
        weight: "14 oz",
        artisan: "Master Artisan",
        rating: 4.8,
        reviews: 26,
        inStock: true,
        featured: false,
        popularity: 78
    },
    {
        id: 38,
        name: "Ceremonial Plate with Diyas",
        category: "decorative",
        price: 28.99,
        originalPrice: 33.99,
        image: "images/pooja-thali-diyas_400.jpg",
        images: ["images/pooja-thali-diyas_800.jpg"],
        description: "Complete ceremonial plate set with diyas and holders. Essential for special occasions and ceremonies.",
        dimensions: "Diameter: 6 inches",
        weight: "10 oz",
        artisan: "Master Artisan",
        rating: 4.7,
        reviews: 33,
        inStock: true,
        featured: false,
        popularity: 80
    },
    {
        id: 39,
        name: "Large Deity Figure",
        category: "deities",
        price: 84.00,
        originalPrice: 95.99,
        image: "images/balaji-large-wooden_400.jpg",
        images: ["images/balaji-large-wooden_800.jpg"],
        description: "Large and detailed deity wooden figurine with elaborate decorations. A statement piece for devotees.",
        dimensions: "Height: 12 inches",
        weight: "23 oz",
        artisan: "Master Artisan",
        rating: 5.0,
        reviews: 15,
        inStock: true,
        featured: true,
        popularity: 88
    },
    {
        id: 40,
        name: "Decorative Bird Figurine",
        category: "animals",
        price: 10.99,
        originalPrice: 13.99,
        image: "images/decorative-bird-parrot_400.jpg",
        images: ["images/decorative-bird-parrot_800.jpg"],
        description: "Colorful decorative parrot with spread wings. Adds a tropical touch to your decor.",
        dimensions: "Height: 4 inches",
        weight: "3 oz",
        artisan: "Master Artisan",
        rating: 4.3,
        reviews: 18,
        inStock: true,
        featured: false,
        popularity: 62
    }
];

// Categories
const categories = [
    { id: "all", name: "All Products", icon: "🎨" },
    { id: "deities", name: "Spiritual Art", icon: "🙏" },
    { id: "animals", name: "House Warming Gifts", icon: "🏠" },
    { id: "village-life", name: "Village Scenes", icon: "🏡" },
    { id: "decorative", name: "Decorative Art", icon: "✨" }
];

// Testimonials with US locations
const testimonials = [
    {
        id: 1,
        name: "Sarah Mitchell",
        location: "New York, NY",
        rating: 5,
        text: "Absolutely stunning craftsmanship! The detail on these pieces is incredible. They make perfect gifts and conversation starters.",
        image: "images/dancing-doll-thanjavur_400.jpg"
    },
    {
        id: 2,
        name: "Michael Chen",
        location: "San Francisco, CA",
        rating: 5,
        text: "I've been collecting handcrafted art for years, and these are some of the most authentic pieces I've found. Amazing quality!",
        image: "images/royal-elephants-ambari_400.jpg"
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        location: "Austin, TX",
        rating: 5,
        text: "Bought the dancing dolls set as a wedding gift. The recipients were absolutely thrilled! Beautiful packaging and fast shipping.",
        image: "images/dancing-dolls-set_400.jpg"
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { products, categories, testimonials };
}
